#!/usr/bin/php -f
<?php
#
# Script to convert the IANA text registration to a pretty HTML format.
#

function html_header($title)
{
  $title = htmlspecialchars($title);

  print("<!doctype html>\n"
  	   ."<html>\n"
	   ."<head>\n"
	   ."  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\n"
	   ."  <title>$title - Printer Working Group</title>\n"
	   ."  <meta http-equiv=\"Content-Type\" "
	   ."content=\"text/html; charset=UTF-8\">\n"
	   ."  <meta name=\"viewport\" content=\"width=device-width\">\n"
	   ."  <link rel=\"stylesheet\" "
	   ."href=\"http://www.google.com/cse/style/look/default.css\" "
	   ."type=\"text/css\">\n"
	   ."  <link rel=\"stylesheet\" type=\"text/css\" href=\"../pwg.css\">\n"
	   ."  <link rel=\"shortcut icon\" href=\"../pwg.ico\" "
	   ."type=\"image/x-icon\">\n"
	   ."  <script type=\"text/javascript\" "
	   ."src=\"http://www.google.com/jsapi\"></script>\n"
	   ."  <script type=\"text/javascript\" src=\"../pwg.js\"></script>\n"
	   ."</head>\n"
	   ."<body onload=\"load_sidebar('../');\">\n"
	   ."<div id=\"PWGPage\">\n"
	   ."  <div id=\"PWGHeader\">\n"
	   ."    <div id=\"PWGHeaderBody\">\n"
	   ."      <div id=\"PWGLogo\"><img src=\"../pwg.png\" alt=\"PWG Logo\" "
	   ."width=\"167\" height=\"78\"></div>\n"
	   ."      <div id=\"PWGSearchForm\">Google Custom Search</div>\n"
	   ."      <div id=\"PWGTitle\">$title</div>\n"
	   ."    </div>\n"
	   ."  </div>\n"
	   ."  <div id=\"PWGBody\">\n"
	   ."    <div id=\"PWGSearchResults\"></div>\n"
	   ."    <div id=\"PWGSideBar\">\n"
	   ."      <div id=\"PWGSideBody\">Loading...</div>\n"
	   ."    </div>\n"
	   ."    <div id=\"PWGContent\">\n"
	   ."      <div id=\"PWGContentBody\">\n");
}

function html_footer()
{
  date_default_timezone_set('America/Los_Angeles');

  $year = date("Y");

  print("	  </div>\n"
	   ."	</div>\n"
	   ."  </div>\n"
	   ."  <div id=\"PWGFooter\">\n"
	   ."    <div id=\"PWGFooterBody\">Comments are owned by the poster. All "
	   ."other material is copyright &copy; 2001-$year The Printer Working "
	   ."Group. All rights reserved. Please contact the "
	   ."<a href=\"mailto:istopwg@gmail.com\">PWG Webmaster</a> to report "
	   ."problems with this site.</div>\n"
	   ."  </div>\n"
	   ."</div>\n"
	   ."</body>\n"
	   ."</html>\n");
}

# Build a list of regular expressions to convert document references to
# hyperlinks...
$pwg5100s = array(
  "PWG5100.1" => "cs-ippfinishings10-20010205-5100.1.pdf",
  "PWG5100.2" => "cs-ippoutputbin10-20010207-5100.2.pdf",
  "PWG5100.3" => "cs-ippprodprint10-20010212-5100.3.pdf",
  "PWG5100.5" => "cs-ippdocobject10-20031031-5100.5.pdf",
  "PWG5100.6" => "cs-ipppageoverride10-20031031-5100.6.pdf",
  "PWG5100.7" => "cs-ippjobext10-20031031-5100.7.pdf",
  "PWG5100.8" => "cs-ippactuals10-20030313-5100.8.pdf",
  "PWG5100.9" => "cs-ippstate10-20090731-5100.9.pdf",
  "PWG5100.11" => "cs-ippjobprinterext10-20101030-5100.11.pdf",
  "PWG5100.12" => "cs-ipp20-20110214-5100.12.pdf"
);

$pattern = array(
  "/\\[RFC([0-9]+)\\]/",		// Standard RFC reference
  "/^- (.*)\$/",			// Table-of-contents
  "/^Registry Name: (.*)\$/",		// Headings
  "/^  - (.*)\$/",			// Table-of-contents subs
  "/^(.*) attributes:\$/"		// Sub-headings
);
$replace = array(
  "[<a href=\"http://tools.ietf.org/html/rfc\\1\">RFC\\1</a>]",
  "- <a href=\"#\\1\">\\1</a>",
  "Registry Name: <a name=\"\\1\">\\1</a>",
  "  - <a href=\"#\\1\">\\1</a>",
  "<a name=\"\\1\">\\1</a> attributes:"
);

foreach ($pwg5100s as $document => $filename)
{
  $pattern[sizeof($pattern)] = "/\\[" . str_replace(".", "\\.", $document) . "\\]/";
  $replace[sizeof($replace)] = "[<a href=\"ftp://ftp.pwg.org/pub/pwg/candidates/$filename\">$document</a>]";
}

# Create the HTML and send it to stdout...
html_header("Internet Printing Protocol (IPP) Registrations");

print("<pre>\n");
$fp = fopen("ipp-registrations.txt", "r");
while ($line = fgets($fp, 1024))
{
  $line = preg_replace($pattern, $replace, htmlspecialchars(rtrim($line)));

  print("$line\n");
}
print("</pre>\n");

html_footer();

?>
